fix: Don't pass any argument to is_python_build due to deprecation since Python 3.12
See here for the deprecation: https://github.com/python/cpython/commit/067597522a9002f3b8aff7f46033f10acb2381e4#diff-d593bd299ba58e440ba411ffa0640ccd9d20d518b0cf2644ed4bdb75a82a3e70

The argument is removed in Python 3.15 and in Python 3.14 the import of warnings results in a loop in the import machinery (similar to 3e7f2e9):

Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/home/cburr/Development/conda-forge/pycurl-feedstock/output/bld/rattler-build_pycurl_1755835374/build_env/venv/lib/site.py", line 177, in <module>
  File "/home/cburr/Development/conda-forge/pycurl-feedstock/output/bld/rattler-build_pycurl_1755835374/build_env/venv/lib/site.py", line 122, in __init__
  File "/home/cburr/Development/conda-forge/pycurl-feedstock/output/bld/rattler-build_pycurl_1755835374/build_env/venv/lib/site.py", line 170, in manually_patch_loaded
  File "/home/cburr/Development/conda-forge/pycurl-feedstock/output/bld/rattler-build_pycurl_1755835374/build_env/venv/lib/site.py", line 56, in _patch_module
  File "/home/cburr/Development/conda-forge/pycurl-feedstock/output/bld/rattler-build_pycurl_1755835374/build_env/venv/lib/sysconfig-patch.py", line 5, in <module>
  File "/home/cburr/Development/conda-forge/pycurl-feedstock/output/bld/rattler-build_pycurl_1755835374/build_env/lib/python3.14/sysconfig/__init__.py", line 225, in is_python_build
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1333, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1267, in _find_spec
  File "/home/cburr/Development/conda-forge/pycurl-feedstock/output/bld/rattler-build_pycurl_1755835374/build_env/venv/lib/importlib-machinery-patch.py", line 18, in _PathFinder_find_spec
  File "/home/cburr/Development/conda-forge/pycurl-feedstock/output/bld/rattler-build_pycurl_1755835374/build_env/lib/python3.14/sysconfig/__init__.py", line 507, in get_path
  File "/home/cburr/Development/conda-forge/pycurl-feedstock/output/bld/rattler-build_pycurl_1755835374/build_env/lib/python3.14/sysconfig/__init__.py", line 497, in get_paths
  File "/home/cburr/Development/conda-forge/pycurl-feedstock/output/bld/rattler-build_pycurl_1755835374/build_env/lib/python3.14/sysconfig/__init__.py", line 276, in _expand_vars
  File "/home/cburr/Development/conda-forge/pycurl-feedstock/output/bld/rattler-build_pycurl_1755835374/build_env/lib/python3.14/sysconfig/__init__.py", line 625, in get_config_vars
  File "/home/cburr/Development/conda-forge/pycurl-feedstock/output/bld/rattler-build_pycurl_1755835374/build_env/lib/python3.14/sysconfig/__init__.py", line 525, in _init_config_vars
  File "/home/cburr/Development/conda-forge/pycurl-feedstock/output/bld/rattler-build_pycurl_1755835374/build_env/lib/python3.14/sysconfig/__init__.py", line 393, in _init_posix
  File "/home/cburr/Development/conda-forge/pycurl-feedstock/output/bld/rattler-build_pycurl_1755835374/build_env/lib/python3.14/sysconfig/__init__.py", line 373, in _get_sysconfigdata
  File "/home/cburr/Development/conda-forge/pycurl-feedstock/output/bld/rattler-build_pycurl_1755835374/build_env/lib/python3.14/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1333, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1267, in _find_spec
  File "/home/cburr/Development/conda-forge/pycurl-feedstock/output/bld/rattler-build_pycurl_1755835374/build_env/venv/lib/importlib-machinery-patch.py", line 18, in _PathFinder_find_spec
  File "/home/cburr/Development/conda-forge/pycurl-feedstock/output/bld/rattler-build_pycurl_1755835374/build_env/lib/python3.14/sysconfig/__init__.py", line 507, in get_path
  File "/home/cburr/Development/conda-forge/pycurl-feedstock/output/bld/rattler-build_pycurl_1755835374/build_env/lib/python3.14/sysconfig/__init__.py", line 497, in get_paths
  File "/home/cburr/Development/conda-forge/pycurl-feedstock/output/bld/rattler-build_pycurl_1755835374/build_env/lib/python3.14/sysconfig/__init__.py", line 286, in _expand_vars
  File "/home/cburr/Development/conda-forge/pycurl-feedstock/output/bld/rattler-build_pycurl_1755835374/build_env/lib/python3.14/sysconfig/__init__.py", line 262, in _subst_vars
AttributeError: 'installed_base'